/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tepach;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony Tepach
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private Archivo archivo;
    private Dividir dividir;

    public App() {
        initComponents();
        archivo = new Archivo();
        dividir = new Dividir();
    }
    private String ruta;
    private int cantidad;
    private long num_archivo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_cargartxt = new javax.swing.JButton();
        jtxt_ruta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLbl_numlineas = new javax.swing.JLabel();
        jtf_cantidaddetxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtf_dvidiren = new javax.swing.JTextField();
        jb_partir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Particionar bobinas");

        JB_cargartxt.setText("Cargar BD");
        JB_cargartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cargartxtActionPerformed(evt);
            }
        });

        jPanel1.setEnabled(false);

        jLbl_numlineas.setText("Num de lineas");

        jtf_cantidaddetxt.setEditable(false);
        jtf_cantidaddetxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_cantidaddetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Cantidad de folios por bobina");

        jtf_dvidiren.setEditable(false);
        jtf_dvidiren.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_dvidiren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_dvidirenActionPerformed(evt);
            }
        });

        jb_partir.setText("Particionar");
        jb_partir.setEnabled(false);
        jb_partir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_partirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_cantidaddetxt)
                    .addComponent(jLbl_numlineas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jtf_dvidiren))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_partir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_numlineas)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_cantidaddetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_dvidiren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_partir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxt_ruta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_cargartxt)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_cargartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jtxt_ruta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JB_cargartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cargartxtActionPerformed
        ruta = archivo.leer(this);
        jtxt_ruta.setText(ruta);
        jtxt_ruta.setEditable(false);
        num_archivo = archivo.numLineas(ruta);
        jtf_cantidaddetxt.setText(String.valueOf(num_archivo));
        String concat = jLbl_numlineas.getText().concat(" de " + archivo.nomTxt(ruta));
        jLbl_numlineas.setText(concat);
        jtf_dvidiren.setEditable(true);

        jb_partir.setEnabled(true);
    }//GEN-LAST:event_JB_cargartxtActionPerformed

    private void jb_partirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_partirActionPerformed
        // TODO add your handling code here:
        if (!jtf_dvidiren.getText().isEmpty()) {
            cantidad = Integer.parseInt(jtf_dvidiren.getText());
            if (!(cantidad > num_archivo)) {
                int division = (int) (num_archivo / cantidad);
                    if (num_archivo%cantidad != 0) {
                    division=division+1;
                }
                JOptionPane.showMessageDialog(rootPane, "Se crearan " + division + " archivos en la ruta: \n" + archivo.carpetaTxt(ruta), "Información", JOptionPane.INFORMATION_MESSAGE);
                String guarda_en=archivo.carpetaTxt(ruta);
                dividir.particiona(ruta, guarda_en, cantidad);
                
                           }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ingresa la cantidad de lineas por archivo");
        }

    }//GEN-LAST:event_jb_partirActionPerformed

    private void jtf_dvidirenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_dvidirenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dvidirenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_cargartxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbl_numlineas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_partir;
    private javax.swing.JTextField jtf_cantidaddetxt;
    private javax.swing.JTextField jtf_dvidiren;
    private javax.swing.JTextField jtxt_ruta;
    // End of variables declaration//GEN-END:variables
}
